################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Configurations/Debug \
. \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Service/CpuGeneric/If \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/Service/CpuGeneric/SysSe/General \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/Service/CpuGeneric/SysSe/Time \
Libraries/iLLD/TC27D/Tricore/Asclin/Asc \
Libraries/iLLD/TC27D/Tricore/Asclin/Lin \
Libraries/iLLD/TC27D/Tricore/Asclin/Spi \
Libraries/iLLD/TC27D/Tricore/Asclin/Std \
Libraries/iLLD/TC27D/Tricore/Ccu6/Icu \
Libraries/iLLD/TC27D/Tricore/Ccu6/PwmBc \
Libraries/iLLD/TC27D/Tricore/Ccu6/PwmHl \
Libraries/iLLD/TC27D/Tricore/Ccu6/Std \
Libraries/iLLD/TC27D/Tricore/Ccu6/TPwm \
Libraries/iLLD/TC27D/Tricore/Ccu6/Timer \
Libraries/iLLD/TC27D/Tricore/Ccu6/TimerWithTrigger \
Libraries/iLLD/TC27D/Tricore/Cif/Cam \
Libraries/iLLD/TC27D/Tricore/Cif/Std \
Libraries/iLLD/TC27D/Tricore/Cpu/CStart \
Libraries/iLLD/TC27D/Tricore/Cpu/Irq \
Libraries/iLLD/TC27D/Tricore/Cpu/Std \
Libraries/iLLD/TC27D/Tricore/Cpu/Trap \
Libraries/iLLD/TC27D/Tricore/Dma/Dma \
Libraries/iLLD/TC27D/Tricore/Dma/Std \
Libraries/iLLD/TC27D/Tricore/Dsadc/Dsadc \
Libraries/iLLD/TC27D/Tricore/Dsadc/Rdc \
Libraries/iLLD/TC27D/Tricore/Dsadc/Std \
Libraries/iLLD/TC27D/Tricore/Dts/Dts \
Libraries/iLLD/TC27D/Tricore/Dts/Std \
Libraries/iLLD/TC27D/Tricore/Emem/Std \
Libraries/iLLD/TC27D/Tricore/Eray/Eray \
Libraries/iLLD/TC27D/Tricore/Eray/Std \
Libraries/iLLD/TC27D/Tricore/Eth/Phy_Pef7071 \
Libraries/iLLD/TC27D/Tricore/Eth/Std \
Libraries/iLLD/TC27D/Tricore/Fce/Crc \
Libraries/iLLD/TC27D/Tricore/Fce/Std \
Libraries/iLLD/TC27D/Tricore/Flash/Std \
Libraries/iLLD/TC27D/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC27D/Tricore/Gpt12/Std \
Libraries/iLLD/TC27D/Tricore/Gtm/Atom/Pwm \
Libraries/iLLD/TC27D/Tricore/Gtm/Atom/PwmHl \
Libraries/iLLD/TC27D/Tricore/Gtm/Atom/Timer \
Libraries/iLLD/TC27D/Tricore/Gtm/Std \
Libraries/iLLD/TC27D/Tricore/Gtm/Tim/In \
Libraries/iLLD/TC27D/Tricore/Gtm/Tom/Pwm \
Libraries/iLLD/TC27D/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC27D/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC27D/Tricore/Gtm/Trig \
Libraries/iLLD/TC27D/Tricore/Hssl/Hssl \
Libraries/iLLD/TC27D/Tricore/Hssl/Std \
Libraries/iLLD/TC27D/Tricore/I2c/I2c \
Libraries/iLLD/TC27D/Tricore/I2c/Std \
Libraries/iLLD/TC27D/Tricore/Iom/Driver \
Libraries/iLLD/TC27D/Tricore/Iom/Std \
Libraries/iLLD/TC27D/Tricore/Msc/Msc \
Libraries/iLLD/TC27D/Tricore/Msc/Std \
Libraries/iLLD/TC27D/Tricore/Mtu/Std \
Libraries/iLLD/TC27D/Tricore/Multican/Can \
Libraries/iLLD/TC27D/Tricore/Multican/Std \
Libraries/iLLD/TC27D/Tricore/Port/Io \
Libraries/iLLD/TC27D/Tricore/Port/Std \
Libraries/iLLD/TC27D/Tricore/Psi5/Psi5 \
Libraries/iLLD/TC27D/Tricore/Psi5/Std \
Libraries/iLLD/TC27D/Tricore/Psi5s/Psi5s \
Libraries/iLLD/TC27D/Tricore/Psi5s/Std \
Libraries/iLLD/TC27D/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC27D/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC27D/Tricore/Qspi/Std \
Libraries/iLLD/TC27D/Tricore/Scu/Std \
Libraries/iLLD/TC27D/Tricore/Sent/Sent \
Libraries/iLLD/TC27D/Tricore/Sent/Std \
Libraries/iLLD/TC27D/Tricore/Smu/Std \
Libraries/iLLD/TC27D/Tricore/Src/Std \
Libraries/iLLD/TC27D/Tricore/Stm/Std \
Libraries/iLLD/TC27D/Tricore/Stm/Timer \
Libraries/iLLD/TC27D/Tricore/Vadc/Adc \
Libraries/iLLD/TC27D/Tricore/Vadc/Std \
Libraries/iLLD/TC27D/Tricore/_Impl \
Libraries/iLLD/TC27D/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC27D/Tricore/_Lib/InternalMux \
Libraries/iLLD/TC27D/Tricore/_PinMap \

